apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/hb-team-001/kube-mirror:heptioImages.ksGuestbookDemo.v02
        name: guestbook-ui
        ports:
        - containerPort: 80
